# Generated by Django 5.1.7 on 2025-04-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recetas', '0004_alter_recetaingrediente_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha_venta', models.DateField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos_vendidos', models.ManyToManyField(related_name='ventas', to='recetas.receta')),
            ],
        ),
    ]
