# Generated by Django 5.1.7 on 2025-04-01 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='costo_decoracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='venta',
            name='costo_empaque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='venta',
            name='hora_venta',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venta',
            name='horas_trabajadas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
