# Generated by Django 5.1.7 on 2025-04-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_venta_total_venta_venta_costo_decoracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
