# Generated by Django 5.1.7 on 2025-04-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_total_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total_venta',
        ),
    ]
