# Generated by Django 5.1.7 on 2025-03-31 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='precio_unitario',
        ),
    ]
