# Generated by Django 5.1.7 on 2025-03-31 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_remove_receta_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaingrediente',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_relacionados', to='recetas.receta'),
        ),
    ]
