# Generated by Django 5.1.7 on 2025-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad', models.CharField(choices=[('g', 'gramos'), ('ml', 'mililitros'), ('unidad', 'unidad'), ('kg', 'kilogramos')], max_length=20)),
                ('distribuidor', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
    ]
