# Generated by Django 5.1.7 on 2025-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='unidad',
            field=models.CharField(choices=[('g', 'gramos'), ('ml', 'mililitros'), ('lt', 'litro'), ('unidad', 'unidad'), ('kg', 'kilogramos')], max_length=20),
        ),
    ]
